# Project 1 group 15 #

### Exercise 1: Finite-precision arithmetic ###

#### part 1 ####

In [2]:
import sys
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)


max: the largest number possible

min: the smalles number possible 

max_exp: the largest bit size. Referse to the lagest exponential possible for => $2^{max exp}$

min_exp: the smallest bit size. Referse to the smallest exponential possible for => $2^{min exp}$

#### part 2 ####

In [29]:
max = (2-2**-52)*(2**1023)
min = 2**(-1022)
epsilon = 2**-52
print("max: ", max)
print("min: ", min)
print("epsilon: ", epsilon)



max:  1.7976931348623157e+308
min:  2.2250738585072014e-308
epsilon:  2.220446049250313e-16


#### part 3 ####

In [30]:
0.1+0.2

0.30000000000000004

As shown above the $0.1 + 0.2 \neq 0.3 $.
This is because numbers are represented as a finit number of bits. (typacly 64-bit). Where the first bit position is the sign, the next 11 bits is the exponent and the last 52 bits is the fraction. This causes some rounding error for floating points as representing some decimals requires an infinite number of digits.

#### part 4 ####

In [32]:
a = 0.1
b = 0.2
c = 0.1 + 0.2
if c == 0.3:
    print("==, opperator workes and gives true")
else:
    print("==, opperator does not work and gives false")

if (c - 0.3) < 0.000001:
    print("<, opperato works and gives true")
else:

    print("<, does not work and gives false")


==, opperator does not work and gives false
<, opperato works and gives true


For the example above where $0.1 + 0.2 \neq 0.3$ it is clare that for some cases using the $==$ opperator will give some errors. this is why you should not use this opperator when dealing with floating points. as shown in the code above we can see that == opperator does not work. an alternative method would be the close enoght method, where we define a tolerance. in this case 0.000001 witch is vary small. 

### Exercise 2: Get up to speed with NumPy ###

Native Python list of the same size as x and holding the same values.

In [1]:
#### part 1 ####
import numpy as np
my_list = []*10
my_list = [0., 0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,0.66666667, 0.77777778, 0.88888889, 1. ]
output_list1 = [np.exp (i) for i in my_list]
output_list2 = [np.exp (-i) for i in my_list]
print("list np.exp(i)", output_list1)
print("list np.exp(-i)", output_list2)

list np.exp(i) [1.0, 1.1175190675001758, 1.2488488662264625, 1.395612420434048, 1.5596234906751207, 1.74290900637972, 1.9477340475471228, 2.1766299365532036, 2.432425456989903, 2.718281828459045]
list np.exp(-i) [1.0, 0.8948393178086357, 0.8007374046962245, 0.7165313129622269, 0.6411803912796452, 0.5737534181874177, 0.5134171173212017, 0.45942582301498036, 0.411112290050396, 0.36787944117144233]


a.Explain what each line of code does

In [2]:
#### part 2 ####
import numpy as np
np.zeros(20) # array with 20 elements equal to zero
np.ones(20) # array with 20 elements equal to one
np.linspace(0, 10, 11) # Return evenly spaced numbers over a specified interval.[start,stop, num= number of evenlly spaced samples]
np.linspace(0, 10, 11, endpoint=False) # Same as above but the stop will not be on the last element. In this case, not on 10
vector1 = np.arange(5) + 1
print(vector1)
2*vector1

[1 2 3 4 5]


array([ 2,  4,  6,  8, 10])

Produce same using Python lists

In [3]:
list_of_zeroes = [0]*20
print(list_of_zeroes)

list_of_ones = [1]*20
print(list_of_ones)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [8]:
#### part 3 ####
array_of_numbers = np.array([4, 8, 15, 16, 23, 42])
nnz = np.count_nonzero(array_of_numbers)
print(f’There are {nnz} non-zero numbers in the array.’)
is_even = (array_of_numbers % 2 == 0)
is_greater_than_17 = (array_of_numbers > 17)
is_even_and_greater_than_17 = is_even & is_greater_than_17

SyntaxError: invalid character '’' (U+2019) (Temp/ipykernel_3860/1191253664.py, line 4)

Reason for failure: The code has failed as it occurs when we use an invalid character in our code or a result of copy-pasting.

In [9]:
#### part 3 Corrected code ####
array_of_numbers = np.array([4, 8, 15, 16, 23, 42])
nnz = np.count_nonzero(array_of_numbers)
print(f'There are {nnz} non-zero numbers in the array.')
is_even = (array_of_numbers % 2 == 0)
is_greater_than_17 = (array_of_numbers > 17)
is_even_and_greater_than_17 = is_even & is_greater_than_17

There are 6 non-zero numbers in the array.


In [10]:
##Part3 b##
is_even_and_greater_than_17 = is_even and is_greater_than_17
print(array_of_numbers % 2 == 0 & array_of_numbers > 17)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Reason for failure: The error occurs because instead of evaluating single values, we are evaluating on more than one element, therefore there is ambiguity in how to determine if the condition is true or not. We are evaluating multiple elements in the boolean context.

In [11]:
##Corrected Code##
is_even_and_greater_than_17 = is_even.any() and is_greater_than_17.any()
print(array_of_numbers % 2 == 0 & array_of_numbers > 17)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### part 4 ####

In [12]:
np.where(array_of_numbers > 17)[0] # Returns the indices of the elements where value is greater then 17

array([4, 5], dtype=int64)

In [13]:
np.where(array_of_numbers > 17, 1, 0)#numpy.where(condition[, x, y]), in this case it return 1 if the condition is true . If False returns 0.

array([0, 0, 0, 0, 1, 1])

### Exercise 3, Part I: Finite Differences (FD) with Functions ###

#### part 1 ####

#### part 2 ####

#### part 3 ####

#### part 4 ####

#### part 5 ####

###  Exercise 3, Part II: FD with Classes ###

#### part 1 ####

#### part 2 ####

### Exercise 4: A song of ice and fire?


#### part 1 ####

#### part 2 ####

#### part 3 ####

#### part 4 ####